# Generated by Django 4.1.1 on 2023-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
