# Generated by Django 4.1.1 on 2023-03-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
